name: API Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  RunTest:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Execute API tests
      run: ./gradlew clean runApiTests

    # Debugging untuk memastikan laporan dibuat
    - name: Debug report directory
      run: ls -R reports || true

    # Pastikan index.html ada sebelum menyalinnya
    - name: Ensure index.html exists
      run: |
        if [ ! -f reports/api-tests/index.html ]; then
          echo "index.html not found! Listing reports/api-tests directory:"
          ls -l reports/api-tests
          exit 1
        fi

    # Tambahkan .nojekyll agar GitHub Pages tidak mengabaikan file statis
    - name: Disable Jekyll
      run: touch reports/.nojekyll

    # Deploy ke GitHub Pages
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: gh-pages
        publish_dir: reports
