name: API Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  RunTest-API:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Download repo
    - uses: actions/checkout@v4

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Install Chrome browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    # Setup Gradlew
    - name: Setup Gradlew
      run: chmod +x gradlew

    # Execute API tests
    - name: Execute API tests
      run: ./gradlew clean runApiTests

    # Pastikan folder laporan API tests sudah ada
    - name: Ensure API test reports directory exists
      run: mkdir -p reports/api-tests

    # Archive Test Result
    - name: Archive Allure Report
      uses: actions/upload-artifact@v4.6.0
      if: always()
      with:
        name: Allure Report
        path: reports/api-tests

    # Disable Jekyll agar GitHub Pages dapat membaca semua file statis
    - name: Disable Jekyll
      run: touch reports/api-tests/.nojekyll

    # Pastikan index.html ada di folder api-tests
    - name: Copy index.html
      run: cp reports/index.html reports/api-tests/index.html || echo "index.html not found, skipping copy"

    # Deploy ke GitHub Pages (API Test)
    - name: Deploy API Test Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: gh-pages
        publish_dir: reports/api-tests
        destination_dir: api-tests
