name: Selenium Web UI Test

on:
  workflow_run:
    workflows: ["API Test"]
    types:
      - completed

jobs:
  RunTest-UI:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Download repo
    - uses: actions/checkout@v4

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    # Setup Gradlew
    - name: Setup Gradlew
      run: chmod +x gradlew

    # Execute Gradle command for running Cucumber test
    - name: Execute UI tests
      run: ./gradlew cucumberChrome

    # Pastikan folder laporan UI tests sudah ada
    - name: Ensure UI test reports directory exists
      run: mkdir -p reports/ui-tests

    # Archive UI Test Result as Artifact
    - name: Archive UI Test Result as Artifact
      uses: actions/upload-artifact@v4.6.0
      if: always()
      with:
        name: ui-test-report-artifact  # Menyebutkan nama artifact dengan jelas
        path: reports/ui-tests        # Folder laporan UI test

    # Disable Jekyll to allow GitHub Pages to serve all files
    - name: Disable Jekyll
      run: touch reports/ui-tests/.nojekyll

    # Pastikan index.html ada di folder ui-tests
    - name: Copy index.html
      run: cp reports/web-UI/index.html reports/ui-tests/index.html || echo "index.html not found, skipping copy"

    # Deploy ke GitHub Pages (UI Test)
    - name: Deploy UI Test Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: gh-pages
        publish_dir: reports/web-UI  # Sumber laporan di branch master
        destination_dir: ui-tests    # Tujuan di branch gh-pages
